version: '2'

services:
  app:
    image: 'currency-history-app:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8082:8082"
    depends_on:
      - db
      - currencyg
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  currencyg:
    image: currency-generator-app:latest
    container_name: currencyg
    build:
      context: C:\Users\Artem\IdeaProjects\currency-generator
    ports:
      - "8081:8081"



